#!/bin/sh

TOGGLE=$HOME/.config/i3/.togglempd
#res=""
#resu=""
if [ ! -e $TOGGLE ]; then
    touch $TOGGLE
    mpd
    notify-send MPD "mpd already on"

    #i3-msg 'workspace 7, move workspace to output VGA-0'
    #sleep 1
    
    #res=`wmctrl -lx | awk '{if ($3 == "kittycava.kittycava") print "OK"}'`
    #[[ ! $res == "OK" ]] && kitty --class kittycava cava &

    #resu=`wmctrl -lx | awk '{if ($3 == "kittyclock.kittyclock") print "OK"}'`
    #[[ ! $resu == "OK" ]] && kitty --class kittyclock tty-clock -c -C 3 -r &
    

else
    rm $TOGGLE
    mpd --kill
    notify-send MPD "mpd killed succesfully"
fi
